# Generated by Django 3.0.4 on 2020-03-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.IntegerField()),
                ('fuel', models.CharField(choices=[(None, '(Unknown)'), (1, 'Water'), (2, 'Natural Gas'), (3, 'Electricity')], max_length=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Building')),
            ],
        ),
        migrations.CreateModel(
            name='MetersReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reading_date_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Meters')),
            ],
        ),
    ]
