# Generated by Django 3.0.4 on 2020-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='meters',
            unique_together={('building', 'meter_id')},
        ),
        migrations.AlterUniqueTogether(
            name='metersreadings',
            unique_together={('meter', 'reading_date_time')},
        ),
    ]
