# Generated by Django 3.0.4 on 2020-03-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200308_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['building_id']},
        ),
        migrations.AlterField(
            model_name='meters',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='rest_api.Building'),
        ),
        migrations.AlterField(
            model_name='metersreadings',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='rest_api.Meters'),
        ),
    ]
