# Generated by Django 3.0.4 on 2020-03-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200310_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metersreadings',
            options={'ordering': ('meter', 'reading_date_time')},
        ),
    ]
